## docker-compose.yml largely lifted from https://github.com/dodeeric/omeka-s-docker/blob/master/docker-compose-traefik.yml
## The following syntax was VERIFIED on 10-June-2019.  Do NOT change it without careful consideration!

version: '3.2'

networks:
  private:
  public:
    external:
      name: traefik_webgateway

services:

  ## This whoami service is lifted from Jeff Geerline and https://github.com/geerlingguy/docker-examples/blob/master/traefik/docker-compose.yml.  Use it for proxy testing only.
  ## The following syntax was VERIFIED on 10-June-2019.  Do NOT change it without careful consideration!

  whoami:
    image: emilevauge/whoami
    networks:
      - public
      - private
    labels:
      traefik.backend: whoami
      traefik.port: 80
      traefik.docker.network: traefik_webgateway  ## Note that specifying "public" here does NOT work!
      traefik.frontend.rule: "Host: dgdocker2.grinnell.edu; PathPrefixStrip: /whoami"
    restart: always

  mariadb:
    image: mariadb:latest
    restart: always
    networks:
      - private
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: blabla
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
    labels:
      traefik.enable: false

  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - private
      - public
    links:
      - mariadb:db
    labels:
      traefik.backend: pma
      traefik.frontend.rule: "Host: dgdocker2.grinnell.edu; PathPrefixStrip: /pma"
      traefik.docker.network: traefik_webgateway  ## Note that specifying "public" here does NOT work!
      traefik.port: 80
      # - "traefik.frontend.rule=Host:pma.localhost"

  omeka:
    depends_on:
      - mariadb
    image: dodeeric/omeka-s:latest
    restart: always
    networks:
      - private
      - public
    links:
      - mariadb:db
    volumes:
      - omeka:/var/www/html/volume
    labels:
      traefik.backend: omeka
      traefik.frontend.rule: "Host: omeka-s.grinnell.edu"
      traefik.docker.network: traefik_webgateway  ## Note that specifying "public" here does NOT work!
      traefik.port: 80
      # - "traefik.frontend.rule=Host:omeka.localhost"

#   # gramps:
#   #   image: httpd:latest
#   #   restart: always
#   #   networks:
#   #     - network1
#   #   volumes:
#   #     - gramps:/usr/local/apache2/htdocs
#   #   labels:
#   #     - "traefik.backend=gramps"
#   #     - "traefik.frontend.rule=Host:gramps.dodeeric.be"
#
#   # traefik:
#   #   image: traefik:latest
#   #   restart: always
#   #   networks:
#   #     - network1
#   #   command: --web --docker --docker.domain=dodeeric.be
#   #   ports:
#   #     - "80:80"
#   #     - "443:443"
#   #     - "8080:8080"
#   #   volumes:
#   #     - /var/run/docker.sock:/var/run/docker.sock
#
volumes:
  mariadb:
  omeka:
  # gramps:
