version: "3"

## This is the "mariadb" and "pma" (PHPMyAdmin) portions of dodeeric's original
##   omeka-s configuration, mixed with a Dockerfile and `docker run` command
##   lifted from https://hub.docker.com/r/boredland/omeka-s-docker/
## This is made to run as omeka.localadmin from a `localdomain` "dockerized-server"
##   configuration.

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    networks:
      - internal
    volumes:
      - mariadb:/var/lib/mysql
      # - ./omeka.sql:/docker-entrypoint-initdb.d/omeka.sql  ## This line, when enabled, will replace your database with an archive copy.  Use with caution!
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_OMEKA_DATABASE}
      MYSQL_USER: ${MYSQL_OMEKA_USER}
      MYSQL_PASSWORD: ${MYSQL_OMEKA_PASSWORD}

  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    restart: always
    networks:
      - web
      - internal
    links:
      - mariadb:db
    labels:
      - "traefik.backend=pma"
      - traefik.docker.network=web
      - traefik.enable=true
      - "traefik.frontend.rule=Host:pma.localdomain"
## The /path addressing approach attempted below did not work properly.  Switched to new pma2.grinnell.edu subdomain on 11-Sep-2019
#      - "traefik.frontend.rule=PathPrefixStrip:/pma"
#      - "traefik.frontend.redirect.regex=^(.*)/pma$$"
#      - "traefik.frontend.redirect.replacement=$$1/pma/"
#      - "traefik.frontend.rule=PathPrefix:/pma;ReplacePathRegex: ^/pma/(.*) /$$1"

  wiki:
    image: mediawiki:latest
    container_name: wiki
    restart: always
    networks:
      - web
      - internal
    labels:
      - "traefik.backend=wiki"
      - traefik.docker.network=web
      - traefik.enable=true
      - "traefik.frontend.rule=Host:wiki.localdomain"
      
  omeka:
    depends_on:
      - mariadb
    build: .
    # image: mcfatem/omeka-s:gc1.4
    container_name: omeka
    restart: always
    networks:
      - web
      - internal
    links:
      - mariadb:db
    # volumes:
      # - ./database.ini:/var/www/html/config/database.ini
      # - ./files:/var/www/html/files
      # - omeka:/var/www/html
      # - /data/Omeka-S/volume:/var/www/html
    labels:
      - "traefik.backend=omeka"
      - traefik.docker.network=web
      - traefik.enable=true
      - "traefik.frontend.rule=Host:omeka.localdomain"

## This is the "solr" portion of dodeeric's original docker-compose-traefik.yml modified
##   for host "dgdocker2" and the "dockerized-server" configuration running there.

  ## Adding solr per `Using Docker Compose` example at https://docs.docker.com/samples/library/solr/

  solr:
    image: solr:5.5.5
    container_name: solr
    restart: always
    networks:
      - web
      - internal
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    labels:
      - "traefik.backend=solr"
      - "traefik.port=8983"
      - traefik.docker.network=web
      - traefik.enable=true
      - "traefik.frontend.rule=Host:solr.localdomain"
## The /path addressing approach attempted below did not work properly.  Switched to new solr2.grinnell.edu subdomain on 11-Sep-2019
#      - "traefik.frontend.priority=50"
#      - "traefik.frontend.rule=PathPrefixStrip:/solr"
#      - "traefik.frontend.redirect.regex=^(.*)/solr$$"
#      - "traefik.frontend.redirect.replacement=$$1/solr/"
#      - "traefik.frontend.rule=PathPrefix:/solr;ReplacePathRegex: ^/solr/(.*) /$$1"

volumes:
  solr-data:
  mariadb:
  # omeka:

networks:
  web:
    external: true
  internal:
    external: false
