version: "2"

## This is a modified copy of dodeeric's original docker-compose-traefik.yml with
## localhost addresses of:
##
##   - omeka.localdomain
##   - pma.localdomain
##   - solr.localdomain
##
## Note that you can also see the Traefik dashboard at http://omeka.localdomain:8080
##
## These addresses need to be defined/enabled locally with an entry in /etc/hosts of:
##
##    ### For omeka-s-docker
##    127.0.0.1    localhost omeka.localdomain pma.localdomain solr.localdomain
##

services:

  mariadb:
    image: mariadb:latest
    restart: always
    networks:
      - network1
    volumes:
      - mariadb:/var/lib/mysql
#      - ./omeka.sql:/docker-entrypoint-initdb.d/wmi.sql
    environment:
      MYSQL_ROOT_PASSWORD: blabla
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka


  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - network1
    links:
      - mariadb:db
    labels:
      - "traefik.backend=pma"
      - "traefik.frontend.rule=Host:pma.localdomain"

  omeka:
    depends_on:
      - mariadb
    image: mcfatem/omeka-s:gc1.4
    restart: always
    networks:
      - network1
    links:
      - mariadb:db
    volumes:
      - omeka:/var/www/html/volume
    labels:
      - "traefik.backend=omeka"
      - "traefik.frontend.rule=Host:omeka.localdomain"

  ## Adding solr per `Using Docker Compose` example at https://docs.docker.com/samples/library/solr/
  solr:
    image: solr:5.5.5
    restart: always
    networks:
      - network1
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    labels:
      - "traefik.backend=solr"
      - "traefik.port=8983"
      - "traefik.frontend.rule=Host:solr.localdomain"

  traefik:
    image: traefik:latest
    restart: always
    networks:
      - network1
    command: --web --docker --docker.domain=localdomain
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mariadb:
  omeka:
  solr-data:

networks:
  network1:
