<?php
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet/leaflet.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet/leaflet.js', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.draw/leaflet.draw.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.draw/leaflet.draw.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.providers/leaflet-providers.js', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.geosearch/leaflet.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.geosearch/bundle.min.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping-form.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.opacity.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.default-view.js', 'Mapping'));

$mapping = null;
$markers = [];
$itemMedia = [];
if (isset($item)) {
    $mapping = $this->api()
        ->searchOne('mappings', ['item_id' => $item->id()])->getContent();
    $markers = $this->api()
        ->search('mapping_markers', ['item_id' => $item->id()])->getContent();
    $itemMedia = $item->media();
}
?>
<fieldset id="mapping-section" class="section">
    <legend id="mapping-legend"><?php echo $this->translate('Mapping'); ?></legend>
    <div id="mapping-map" style="height:500px;"
        data-mapping="<?php echo $this->escapeHtml(json_encode($mapping)); ?>"
        data-markers="<?php echo $this->escapeHtml(json_encode($markers)); ?>"
    ></div>
    <div id="mapping-marker-image-selector" class="sidebar">
        <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $this->translate('Close Me'); ?></span></a>
        <h3><?php echo $this->translate('Marker Image'); ?></h3>
        <label><input type="radio" class="mapping-marker-image-select" name="marker-image" value="" checked><?php echo $this->translate(' No Image'); ?></label>
        <?php foreach ($itemMedia as $media): ?>
        <?php if ($media->hasThumbnails()): ?>
        <label style="cursor:pointer;">
            <input type="radio" class="mapping-marker-image-select" name="marker-image" style="display:none;"
                value="<?php echo $this->escapeHtml($media->id()); ?>"
                data-media-thumbnail-url="<?php echo $this->escapeHtml($media->thumbnailUrl('medium')); ?>"
                data-media-title="<?php echo $this->escapeHtml($media->displayTitle()); ?>">
            <img src="<?php echo $this->escapeHtml($media->thumbnailUrl('medium')); ?>"
                title="<?php echo $this->escapeHtml($media->displayTitle()); ?>">
        </label>
        <?php endif; ?>
        <?php endforeach; ?>
    </div>
    <div id="mapping-form">
        <input type="hidden" name="o-module-mapping:mapping[o:id]">
        <input type="hidden" name="o-module-mapping:mapping[o-module-mapping:bounds]" value="">
    </div>
</fieldset>

<div class="mapping-marker-popup-content template">
    <div><?php echo $this->translate('Marker Label'); ?></div>
    <input type="text" class="mapping-marker-popup-label" size="30">
    <div class="mapping-marker-popup-image"></div>
    <button class="mapping-marker-popup-image-select"><?php echo $this->translate('Select Marker Image'); ?></button>
</div>
