<?php
$mapping = $this->api()->searchOne('mappings', ['item_id' => $item->id()])->getContent();
$markers = $this->api()->search('mapping_markers', ['item_id' => $item->id()])->getContent();

if (!$mapping && !$markers) {
    return;
}

$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet/leaflet.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet/leaflet.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.providers/leaflet-providers.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping-show.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Mapping'));
?>
<div id="mapping-section" class="section">
    <div id="mapping-map" style="height:500px;"
        data-mapping="<?php echo $this->escapeHtml(json_encode($mapping)); ?>"
    ></div>
</div>

<?php foreach ($markers as $marker): ?>
<?php
$item = $marker->item();
$media = $marker->media();
?>
<div class="mapping-marker-popup-content" style="display:none;"
    data-marker-id="<?php echo $this->escapeHtml($marker->id()); ?>"
    data-marker-lat="<?php echo $this->escapeHtml($marker->lat()); ?>"
    data-marker-lng="<?php echo $this->escapeHtml($marker->lng()); ?>"
>
    <?php if ($marker->label()): ?>
    <h3><?php echo $this->escapeHtml($marker->label()); ?></h3>
    <?php endif; ?>
    <?php if ($media): ?>
    <img src="<?php echo $this->escapeHtml($media->thumbnailUrl('medium')); ?>">
    <div>
        <?php echo sprintf($this->translate('Media: %s'), $media->link($media->displayTitle())); ?>
    </div>
    <?php endif; ?>
    <div>
        <?php echo sprintf($this->translate('Item: %s'), $item->link($item->displayTitle())); ?>
    </div>
</div>
<?php endforeach; ?>
