<?php
$this->headScript()->appendFile($this->assetUrl('js/dspace-connector.js', 'DspaceConnector'));
$this->headLink()->appendStylesheet($this->assetUrl('css/dspace-connector.css', 'DspaceConnector'));
$form->prepare(); 
$escapeHtml = $this->plugin('escapeHtml');
$formElement = $this->plugin('formElement');
$formLabel = $this->plugin('formLabel');
?>

<?php echo $this->pageTitle($this->translate('Dspace Connector'), 1, $this->translate('Import Settings')); ?>
<div id="import" class="section active">
    <?php echo $this->form()->openTag($form); ?>
    <fieldset id='page-actions'>
        <button><?php echo $this->translate("Get collections and communities"); ?></button>
    </fieldset>
<?php echo $this->formCollection($form, false); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>
