<?php 
$form->prepare(); 
$escapeHtml = $this->plugin('escapeHtml');
?>
<?php echo $this->pageTitle($this->translate('Fedora Import'), 1, $this->translate('Import Settings')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->escapeHtml($this->translate('Submit')); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag($form); ?>