# Basic LAMP stack
# - Apache 2.4
# - MySQL 5.6
# - PHP 7.2

version: "2.1"

services:
  # http(s)://VIRTUAL_HOST
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: apache
    depends_on:
      - cli
      - omeka

  mariadb:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mysql
    ## below from https://github.com/dodeeric/omeka-s-docker/blob/master/docker-compose.yml mariadb service
    image: mariadb:latest
    restart: always
    # networks:
    #   - network1
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: blabla
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    ## below from https://github.com/dodeeric/omeka-s-docker/blob/master/docker-compose.yml omeka service
    depends_on:
      - mariadb
    image: dodeeric/omeka-s:latest
    #image: digitalgrinnell/omeka-s:latest
    restart: always
    # networks:
    #   - network1
    ports:
      - "8081:80"
    links:
      - mariadb:db
    volumes:
      - omeka:/var/www/html

  omeka:
    depends_on:
      - mariadb
    image: dodeeric/omeka-s:latest
    restart: always
    # networks:
    #   - network1
    ports:
      - "80:80"
    links:
      - mariadb:db
    volumes:
      - omeka:/var/www/html/volume


  ## pma is entirely from https://github.com/dodeeric/omeka-s-docker/blob/master/docker-compose.yml
  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    # networks:
    #   - network1
    ports:
      - "8080:80"
    links:
      - mariadb:db

  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
#      image: docksal/solr:6.6
    ports:
      - "8983:80"

## entirely from https://github.com/dodeeric/omeka-s-docker/blob/master/docker-compose.yml
volumes:
  mariadb:
  omeka:

# networks:
#   network1:
