version: "2.1"

services:
  # http(s)://VIRTUAL_HOST

  ## This 'web' service should NOT be present in Docksal.  The web server, SSH keys, networking and DNS are all
  ## taken care of automatically in a Docksal stack, so this becomes redundant and unnecessary.
  # web:
  #   extends:
  #     file: ${HOME}/.docksal/stacks/services.yml
  #     service: apache
  #   depends_on:
  #     - cli
  #     - omeka

  mariadb:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mysql
    ## below from https://github.com/dodeeric/omeka-s-docker/blob/master/docker-compose.yml mariadb service
    image: mariadb:latest
    restart: always
    ## The next two lines should NOT be present ANYWHERE in Docksal. The web server, SSH keys, networking and DNS
    ## are all taken care of automatically in a Docksal stack, so this becomes unnecessary throughout the Docksal stack.
    # networks:
    #   - network1
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: blabla
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    ## below from https://github.com/dodeeric/omeka-s-docker/blob/master/docker-compose.yml omeka service
    depends_on:
      - mariadb
    image: dodeeric/omeka-s:latest
    #image: digitalgrinnell/omeka-s:latest
    restart: always
    # networks:
    #   - network1
    ports:
      - "8081:80"
    links:
      - mariadb:db
    volumes:
      - omeka:/var/www/html

  ## This 'omeka' service should NOT be present in Docksal, because it is already present in the `cli` service above.
  ## Note that `cli` uses the same image as this.  Since 'cli' is built from the Omeka-s image, this service
  ## becomes redundant, and it in fact gets in the way since both `cli` and `omeka` want to use port 80.
  # omeka:
  #   depends_on:
  #     - mariadb
  #   image: dodeeric/omeka-s:latest
  #   restart: always
  #   # networks:
  #   #   - network1
  #   ports:
  #     - "80:80"
  #   links:
  #     - mariadb:db
  #   volumes:
  #     - omeka:/var/www/html/volume
  #

  ## pma is entirely from https://github.com/dodeeric/omeka-s-docker/blob/master/docker-compose.yml
  pma:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    # networks:
    #   - network1
    ports:
      - "8080:80"
    links:
      - mariadb:db

  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    image: docksal/solr:6.6
    ports:
      - "8082:8983"

## entirely from https://github.com/dodeeric/omeka-s-docker/blob/master/docker-compose.yml
volumes:
  mariadb:
  omeka:

## The next two lines should NOT be present in Docksal. The web server, SSH keys, networking and DNS are all
## taken care of automatically in a Docksal stack, so this becomes unnecessary throughout the Docksal stack.
# networks:
#   network1:
