# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Omeka-S

on:
  push:
    branches:
      - omeka-s-3.0.2
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://grinnellcollegelibraries.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5b581652f22249adbdc6eb481c554522 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ea94b357e11c4dc6a6e8ba5dc5f1a803 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: grinnellcollegelibraries.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5b581652f22249adbdc6eb481c554522 }}/omeka-s:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Omeka-S'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7e61a469f0dc43d7a439c6e274c71560 }}
        images: 'grinnellcollegelibraries.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5b581652f22249adbdc6eb481c554522 }}/omeka-s:${{ github.sha }}'